name: External GitOps Trigger

on:
  repository_dispatch:
    types: [sync-entities-permissions]

jobs:
  download-and-sync:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Handle sync request
        run: |
          echo "Received sync request from ${{ github.event.client_payload.repo_name }}"
          echo "Triggered by: ${{ github.event.client_payload.triggered_by }}"
      - name: Download JSON from external repository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "📥 Downloading JSON file from external repository..."
          
          # Download the JSON file from the external repository
          curl -H "Authorization: token $GITHUB_TOKEN" \
               -H "Accept: application/vnd.github.v3.raw" \
               -o entities.json \
               -f \
               "https://api.github.com/repos/${{ github.event.client_payload.repo_owner }}/${{ github.event.client_payload.repo_name }}/contents/${{ github.event.client_payload.file_path }}"

          if [ $? -ne 0 ]; then
            echo "❌ Failed to download JSON file"
            exit 1
          fi

          echo "✅ Successfully downloaded JSON file"
          echo "📄 File contents preview:"
          head -20 entities.json
      
      - name: Upload entities.json as artifact
        uses: actions/upload-artifact@v4
        with:
          name: entities-json
          path: entities.json

  call-sync-workflow:
    needs: download-and-sync
    uses: ./.github/workflows/gitops-sync.yml
    with:
      json_file_path: 'entities.json'
