name: GitOps Sync

on:
  workflow_call:
    inputs:
      json_file_path:
        description: 'Path to the JSON file with entities and permissions'
        required: true
        type: string

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: |
          npm install -g typescript ts-node
      - name: Download JSON file
        run: |
          # If the JSON file is in another repository, download it
          # For now, assuming it's passed as input or available in the repo
          echo "JSON file path: ${{ inputs.json_file_path }}"

      - name: Validate JSON file exists
        run: |
          if [ ! -f "${{ inputs.json_file_path }}" ]; then
            echo "❌ JSON file not found: ${{ inputs.json_file_path }}"
            exit 1
          fi
          echo "✅ JSON file found: ${{ inputs.json_file_path }}"

      - name: Report results
        if: always()
        run: |
          echo "📊 GitOps sync completed. Check logs above for details."
