name: GitOps Sync

on:
  workflow_call:
    inputs:
      json_file_path:
        description: 'Path to the JSON file with entities and permissions'
        required: true
        type: string

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Download entities.json artifact
        uses: actions/download-artifact@v4
        with:
          name: entities-json
          path: .

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
      
      - name: Install dependencies
        run: |
          npm install -g typescript ts-node
      
      - name: Validate JSON file exists
        run: |
          if [ ! -f "${{ inputs.json_file_path }}" ]; then
            echo "❌ JSON file not found: ${{ inputs.json_file_path }}"
            exit 1
          fi
          echo "✅ JSON file found: ${{ inputs.json_file_path }}"
          echo "📄 File contents preview:"
          head -100 "${{ inputs.json_file_path }}"

      - name: Report results
        if: always()
        run: |
          echo "📊 GitOps sync completed. Check logs above for details."
